# Manipulating Arrays

Here are two techniques that can be used to change or manipulayte the structure of arrays:
*  Stacking
*  Reshaping

### Stacking

In [2]:
#importing the NumPy library
import numpy as np

# Creating two 1-D arrays with 5 elements using arange
arr_1 = [1,2,3,4,5]
arr_2 = [6,7,8,4,10]


In [3]:
# Horizonal stacking - Appending the elements in the same row
np.hstack((arr_1,arr_2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  4, 10])

In [4]:
# Vertical stacking - Increasing the number of row


# Storing the stacked array for further operations
arr_3 = np.vstack((arr_1,arr_2))
arr_3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  4, 10]])

In [6]:
# Checking the dimensions of the array
arr_3.shape

(2, 5)

In [7]:
# Printing the created array
arr_3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  4, 10]])

In [ ]:
# Number of rows and columns in the array


### Reshaping

In [8]:
# Creating an array of first ten natural numbers
arr_4 = np.arange(1,11)

# Printing the created array
arr_4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# Reshaping the 1D array into a 2D array with 2 elements in five rows
arr_5 = arr_4.reshape(5,2)

In [10]:
# Checking the rows and columns in the created array
arr_5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [11]:
# Creating a 2D array with 4 elements in five rows (elements from 20 to 39)
arr_6 = np.arange(20,40).reshape(5,4)

# Checking the rows and columns in the created array
arr_6

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [ ]:
# Stacking arr_5 and arr_6


In [ ]:
# Check the structure of arr_6


In [ ]:
# Reshape the arr_6 to vertically stack with arr_5 
arr_6 = 
arr_6

In [ ]:
# Stacking arr_5 and arr_6


In [18]:
arr=np.arange(1,11*12+1)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132])

In [20]:
arr2=arr.reshape(11,12)

In [23]:
np.unravel_index(99, arr2.shape)

(8, 3)

In [25]:
p=np.array([[1, 5],
 [3, 7],
 [4, 9]]) 
p

array([[1, 5],
       [3, 7],
       [4, 9]])

In [26]:
np.reshape(p, -1)

array([1, 5, 3, 7, 4, 9])

In [37]:
a=np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [34]:
a[a%2 != 0].reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [38]:

print(a[a%2 == 0].reshape(5, 2))

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]


In [39]:
p=[[1, 5],
 [3, 7],
 [4, 9]]
np.reshape(p, (1, -1))

array([[1, 5, 3, 7, 4, 9]])

In [47]:
#sp: array concat
arr_1 = np.array([[7, 13, 14],[18, 10, 17],[11, 12, 19]])
arr_2 = np.array([16, 6, 1])
arr_3 = np.array([[5, 8, 4, 3]]).reshape(4,1)


# Import NumPy

# Write your code here
arr_4=np.vstack((arr_1,arr_2))

final_array =np.hstack((arr_4,arr_3)) 
final_array

array([[ 7, 13, 14,  5],
       [18, 10, 17,  8],
       [11, 12, 19,  4],
       [16,  6,  1,  3]])